name: 'Glo Move Cards'
description: 'GitHub action to move Glo Boards cards to a column'
branding:
  color: 'blue'
  icon: 'move'
inputs:
  authToken:
    description: Auth token for user
    required: true
  cards:
    description: Array of { cardId, boardId } objects
    required: true
  column:
    description: Name of column to move cards to
    required: true
runs:
  using: 'node12'
  main: 'lib/main.js'
